# Generated by Django 3.1 on 2020-08-13 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('explain', models.TextField(blank=True)),
                ('profile_img', models.ImageField(blank=True, upload_to='contents/creator/profile')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Top', '상의'), ('Bottom', '하의'), ('etc', '기타')], default='none', max_length=10)),
                ('main_img', models.ImageField(blank=True, upload_to='contents/item/<django.db.models.fields.CharField>')),
                ('explain', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppableContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('explain', models.TextField(blank=True)),
                ('background_img', models.ImageField(blank=True, upload_to='contents/shoppable/background')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.creator')),
                ('shoppable_contents', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.shoppablecontents')),
            ],
        ),
        migrations.CreateModel(
            name='Look',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('main_img', models.ImageField(blank=True, upload_to='contents/look/<django.db.models.fields.CharField>')),
                ('like', models.PositiveIntegerField(default=0)),
                ('items', models.ManyToManyField(to='contents.Item')),
                ('youtube_contents', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.youtubecontents')),
            ],
        ),
    ]
