# Generated by Django 3.1 on 2020-08-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_auto_20200824_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('T-shirts', '티셔츠'), ('Hoodie/Sweat shirts', '후드/집업/맨투맨'), ('Shirts/Blouse', '셔츠/블라우스'), ('Knite/Cardigan', '니트/가디건'), ('Outer', '아우터'), ('Pants', '팬츠'), ('Skirt', '스커트'), ('One-piece', '원피스'), ('Sports', '스포츠'), ('Underwear', '언더웨어'), ('Bag', '가방'), ('Wallet/Pouch', '지갑/파우치'), ('Watch', '시계'), ('Hat', '모자'), ('Glass/Sunglass', '안경/선글라스'), ('Jewelry', '쥬얼리'), ('Shocks', '양말/스타킹'), ('Sneakers', '스니커즈'), ('Shoes', '구두'), ('Sandal', '샌들'), ('Boots', '부츠'), ('Shoe care', '슈케어'), ('Men shoes', '남성슈즈'), ('Phone accessories', '휴대폰 액세서리'), ('etc', '기타')], default='none', max_length=50),
        ),
    ]
