# Generated by Django 3.1 on 2020-09-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_auto_20200829_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.URLField(blank=True, help_text='https 로 접속 가능하면 https 로 해주세요.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='look',
            name='main_img_aspect_ratio',
            field=models.FloatField(db_column='main_img_aspect_ratio', default=1.0, help_text='가로길이 나누기 세로길이. 정방형이면 1.', verbose_name='가로/세로비'),
        ),
    ]
