# Generated by Django 3.1 on 2020-09-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200912_1334'),
        ('contents', '0006_auto_20200901_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '상품', 'verbose_name_plural': '상품들'},
        ),
        migrations.AlterModelOptions(
            name='look',
            options={'verbose_name': '장면', 'verbose_name_plural': '장면들'},
        ),
        migrations.AlterModelOptions(
            name='shoppablecontents',
            options={'verbose_name': '퍼플 컨텐츠', 'verbose_name_plural': '퍼플 컨텐츠들'},
        ),
        migrations.AlterModelOptions(
            name='youtubecontents',
            options={'verbose_name': '유튜브 컨텐츠 정보', 'verbose_name_plural': '유튜브 컨텐츠 정보들'},
        ),
        migrations.AddField(
            model_name='look',
            name='liked_users',
            field=models.ManyToManyField(blank=True, to='accounts.IPUserProfile'),
        ),
    ]
