# Generated by Django 3.1.1 on 2020-09-19 03:43

import contents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_shoppablecontents_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='main_img',
            field=models.ImageField(blank=True, upload_to=contents.models.item_img_upload_path),
        ),
        migrations.AlterField(
            model_name='look',
            name='main_img',
            field=models.ImageField(blank=True, upload_to=contents.models.look_img_upload_path),
        ),
    ]
