# Generated by Django 3.1 on 2020-09-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_randomnickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipuserprofile',
            name='liked_looks',
        ),
        migrations.RemoveField(
            model_name='ipuserprofile',
            name='voted_choices',
        ),
    ]
