# Generated by Django 3.1 on 2020-08-17 05:40

import components.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0002_auto_20200813_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('explain', models.TextField(blank=True)),
                ('want_to_promote', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shoppable_contents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.shoppablecontents')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategoryInfoComponent',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.component')),
            ],
            bases=('components.component',),
        ),
        migrations.CreateModel(
            name='LookItemInfoComponent',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.component')),
            ],
            bases=('components.component',),
        ),
        migrations.CreateModel(
            name='VoteComponent',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.component')),
                ('img', models.ImageField(blank=True, upload_to='component/vote/')),
            ],
            bases=('components.component',),
        ),
        migrations.CreateModel(
            name='VoteChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('img', models.ImageField(blank=True, upload_to='component/vote/choice/')),
                ('vote', models.PositiveIntegerField(default=0)),
                ('vote_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.votecomponent')),
            ],
        ),
    ]
