# Generated by Django 3.1 on 2020-08-13 14:13

import components.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('explain', models.TextField(blank=True)),
                ('img', models.ImageField(blank=True, upload_to=components.models.vote_img_upload_path)),
                ('youtube_contents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.youtubecontents')),
            ],
        ),
        migrations.CreateModel(
            name='VoteChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('img', models.ImageField(blank=True, upload_to=components.models.vote_choice_img_upload_path)),
                ('vote_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.votecomponent')),
            ],
        ),
        migrations.CreateModel(
            name='LookItemInfoComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('youtube_contents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.youtubecontents')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategoryInfoComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('youtube_contents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.youtubecontents')),
            ],
        ),
    ]
