# Generated by Django 3.1 on 2020-08-17 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20200817_0822'),
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='shoppable_contents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_set', to='contents.shoppablecontents'),
        ),
        migrations.AlterField(
            model_name='votechoice',
            name='vote_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_choice_set', to='components.votecomponent'),
        ),
    ]
