# Generated by Django 3.1 on 2020-08-29 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_auto_20200824_1501'),
        ('components', '0003_auto_20200824_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookiteminfocomponent',
            name='look',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='component_set', to='contents.look'),
            preserve_default=False,
        ),
    ]
