# Generated by Django 3.1 on 2020-09-12 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_component_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentComponent',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.component')),
                ('img', models.ImageField(blank=True, upload_to='component/comment/')),
                ('img_aspect_ratio', models.FloatField(default=1.0, help_text='가로길이 나누기 세로길이. 정방형이면 1.', verbose_name='가로/세로비')),
            ],
            options={
                'verbose_name': '댓글 컴포넌트',
                'verbose_name_plural': '댓글 컴포넌트',
            },
            bases=('components.component',),
        ),
        migrations.AlterModelOptions(
            name='itemcategoryinfocomponent',
            options={'verbose_name': '카테고리 컴포넌트', 'verbose_name_plural': '카테고리 컴포넌트'},
        ),
        migrations.AlterModelOptions(
            name='lookiteminfocomponent',
            options={'verbose_name': '장면 컴포넌트', 'verbose_name_plural': '장면 컴포넌트'},
        ),
        migrations.AlterModelOptions(
            name='modelinfocomponent',
            options={'verbose_name': '모델정보 컴포넌트', 'verbose_name_plural': '모델정보 컴포넌트'},
        ),
        migrations.AlterModelOptions(
            name='votecomponent',
            options={'verbose_name': '투표 컴포넌트', 'verbose_name_plural': '투표 컴포넌트'},
        ),
        migrations.AlterField(
            model_name='votecomponent',
            name='img_aspect_ratio',
            field=models.FloatField(default=1.0, help_text='가로길이 나누기 세로길이. 정방형이면 1.', verbose_name='가로/세로비'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_writer_name', models.CharField(max_length=30)),
                ('comment', models.TextField(max_length=500)),
                ('like', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_set', to='components.commentcomponent')),
            ],
        ),
    ]
