# Generated by Django 3.1.1 on 2020-09-19 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_comment_liked_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteComponent',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='components.component')),
            ],
            options={
                'verbose_name': '인용구 컴포넌트',
                'verbose_name_plural': '인용구 컴포넌트',
            },
            bases=('components.component',),
        ),
        migrations.AddField(
            model_name='modelinfocomponent',
            name='bottom_unit',
            field=models.CharField(choices=[('size', 'size'), ('inch', 'inch'), ('cm', 'cm'), ('mm', 'mm'), ('m', 'm'), ('kg', 'kg'), ('g', 'g')], default='inch', max_length=10),
        ),
        migrations.AddField(
            model_name='modelinfocomponent',
            name='height_unit',
            field=models.CharField(choices=[('size', 'size'), ('inch', 'inch'), ('cm', 'cm'), ('mm', 'mm'), ('m', 'm'), ('kg', 'kg'), ('g', 'g')], default='cm', max_length=10),
        ),
        migrations.AddField(
            model_name='modelinfocomponent',
            name='shoes_unit',
            field=models.CharField(choices=[('size', 'size'), ('inch', 'inch'), ('cm', 'cm'), ('mm', 'mm'), ('m', 'm'), ('kg', 'kg'), ('g', 'g')], default='mm', max_length=10),
        ),
        migrations.AddField(
            model_name='modelinfocomponent',
            name='top_unit',
            field=models.CharField(choices=[('size', 'size'), ('inch', 'inch'), ('cm', 'cm'), ('mm', 'mm'), ('m', 'm'), ('kg', 'kg'), ('g', 'g')], default='size', max_length=10),
        ),
        migrations.AddField(
            model_name='modelinfocomponent',
            name='weight',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='modelinfocomponent',
            name='weight_unit',
            field=models.CharField(choices=[('size', 'size'), ('inch', 'inch'), ('cm', 'cm'), ('mm', 'mm'), ('m', 'm'), ('kg', 'kg'), ('g', 'g')], default='kg', max_length=10),
        ),
    ]
