# Generated by Django 3.1.1 on 2020-09-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0011_auto_20200919_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '댓글', 'verbose_name_plural': '댓글'},
        ),
        migrations.AlterField(
            model_name='component',
            name='title',
            field=models.CharField(max_length=65),
        ),
    ]
